sudo: required
services:
  - docker

before_install: 
  - docker build -t menomonies/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true menomonies/react-test npm test

after_success:
  - docker build -t menomonies/multi-client ./client
  - docker build -t menomonies/multi-nginx ./nginx
  - docker build -t menomonies/multi-server ./server
  - docker build -t menomonies/multi-worker ./worker

  # Log in to  the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passowrd-stdin
  # Take those image to push them to Docker hub
  - docker push menomonies/multi-client
  - docker push menomonies/multi-nginx
  - docker push menomonies/multi-server
  - docker push menomonies/multi-worker


